# Generated by Django 4.1.4 on 2022-12-26 14:19

from django.db import migrations, models
import saving.models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='tag',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='refrence',
            name='category',
            field=models.ManyToManyField(default=saving.models.Category.get_unkown, to='saving.category'),
        ),
        migrations.AlterField(
            model_name='refrence',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
