# Generated by Django 4.1.4 on 2022-12-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saving', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='id',
        ),
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
